In [15]:
# install the packages we need

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
# load the data

NBA19 = pd.read_excel("Assignment Data/NBA2019odds.xlsx")
NBA19.head()

team               opponent  day  month  year  winodds  \
0  Golden State Warriors        Houston Rockets    4      1  2019     1.27   
1        Houston Rockets  Golden State Warriors    4      1  2019     3.92   
2        New York Knicks     Washington Wizards   17      1  2019     3.52   
3     Washington Wizards        New York Knicks   17      1  2019     1.32   
4         Boston Celtics     Los Angeles Lakers    8      2  2019     1.24   

   loseodds  teampts  oppopts  diff  overtime  home  \
0      3.92      134      135     1         1     1   
1      1.27      135      134     1         1     0   
2      1.32      100      101     1         0     0   
3      3.52      101      100     1         0     1   
4      4.31      128      129     1         0     1   

                           Game(home-away)     HAscore  win prob  win  
0  Golden State Warriors - Houston Rockets  134:135 ET  0.755299    0  
1  Golden State Warriors - Houston Rockets  134:135 ET  0.244701    1  
2     Washington Wizards - New York Knicks     101:100  0.272727    0  
3     Washington Wizards - New York Knicks     101:100  0.727273    1  
4      Boston Celtics - Los Angeles Lakers     128:129  0.776577    0

In [17]:
NBA19['winprob']= 1/(NBA19.winodds) / (1/(NBA19['winodds']) + 1/(NBA19.loseodds))

# filter to have just home 
NBA19= NBA19[NBA19.home ==1]

In [18]:
# get coefficient of win and winprob
np.corrcoef(NBA19.winprob, NBA19.win)

array([[1.        , 0.39652887],
       [0.39652887, 1.        ]])

In [19]:
# get points diff
NBA19['absdiff']= abs(NBA19.teampts - NBA19.oppopts)
np.median(NBA19.absdiff)

9.0

In [20]:
# filter for point diff less then 9 
NBA1= NBA19[NBA19.absdiff < 9]
np.corrcoef(NBA1.winprob, NBA1.win)

array([[1.        , 0.19811648],
       [0.19811648, 1.        ]])

In [21]:
# filter for point diff bigger then 9
NBAh= NBA19[NBA19.absdiff > 9]
np.corrcoef(NBAh.winprob, NBAh.win)

array([[1.        , 0.57647206],
       [0.57647206, 1.        ]])

In [23]:
# filter of OT
NBA_OT = NBA19[NBA19.overtime ==1]
np.corrcoef(NBA_OT.winprob, NBA_OT.win)

array([[1.        , 0.03225853],
       [0.03225853, 1.        ]])

In [24]:
# filter for regulation 
NBA19_reg = NBA19[NBA19.overtime == 0]
np.corrcoef(NBA19_reg.winprob, NBA19_reg.win)

array([[1.       , 0.4144347],
       [0.4144347, 1.       ]])

In [25]:
# filter for year 2018
NBA19_18= NBA19[NBA19.year == 2018]
np.corrcoef(NBA19_18.winprob, NBA19_18.win)

array([[1.        , 0.33824657],
       [0.33824657, 1.        ]])

In [26]:
# filter for year 2019
NBA19_19= NBA19[NBA19.year== 2019]
np.corrcoef(NBA19_19.winprob, NBA19_19.win)

array([[1.        , 0.43797601],
       [0.43797601, 1.        ]])

In [27]:
# filter for each month Oct- April
NBA19_oct= NBA19[NBA19.month == 10]
NBA19_nov= NBA19[NBA19.month == 11]
NBA19_dec= NBA19[NBA19.month == 12]
NBA19_jan= NBA19[NBA19.month == 1]
NBA19_feb= NBA19[NBA19.month == 2]
NBA19_mar= NBA19[NBA19.month == 3]
NBA19_apr= NBA19[NBA19.month == 4]

In [31]:
# get correlation for each month 
print('Oct:', np.corrcoef(NBA19_oct.winprob, NBA19_oct.win))
print('\nNov:', np.corrcoef(NBA19_nov.winprob, NBA19_nov.win))
print('\nDec:', np.corrcoef(NBA19_dec.winprob, NBA19_dec.win))
print('\nJan:', np.corrcoef(NBA19_jan.winprob, NBA19_jan.win))
print('\nFeb:', np.corrcoef(NBA19_feb.winprob, NBA19_feb.win))
print('\nMar:', np.corrcoef(NBA19_mar.winprob, NBA19_mar.win))
print('\nApr:', np.corrcoef(NBA19_apr.winprob, NBA19_apr.win))

Oct: [[1.        0.4132173]
 [0.4132173 1.       ]]

Nov: [[1.         0.31889017]
 [0.31889017 1.        ]]

Dec: [[1.         0.32183843]
 [0.32183843 1.        ]]

Jan: [[1.        0.5035297]
 [0.5035297 1.       ]]

Feb: [[1.         0.37928007]
 [0.37928007 1.        ]]

Mar: [[1.         0.41270836]
 [0.41270836 1.        ]]

Apr: [[1.        0.4554355]
 [0.4554355 1.       ]]
